FROM maven:3.3.9-jdk-8

COPY ./maven-settings.xml /m2/maven-settings.xml

COPY ./core /usr/src/app/core
WORKDIR /usr/src/app/core
RUN mvn -s /m2/maven-settings.xml -Dmaven.test.skip=true clean install

COPY ./trials-model /usr/src/app/trials-model
WORKDIR /usr/src/app/trials-model
RUN mvn -s /m2/maven-settings.xml -Dmaven.test.skip=true clean install

COPY ./trials-ai /usr/src/app/trials-ai
WORKDIR /usr/src/app/trials-ai
RUN mvn -s /m2/maven-settings.xml -Dmaven.test.skip=true clean install

COPY ./trials-engine /usr/src/app/trials-engine
WORKDIR /usr/src/app/trials-engine
RUN mvn -s /m2/maven-settings.xml -Dmaven.test.skip=true clean package shade:shade

CMD ["java", "-jar", "/usr/src/app/trials-engine/target/trials-engine-0.0.1-SNAPSHOT.jar"]