producer:
  image: rgardler/acs-logging-test-simulate
  env_file:
    - ./env.conf

analyzer:
  image: rgardler/acs-logging-test-analyze
  env_file:
    - ./env.conf

rest_enqueue:
  image: rgardler/acs-logging-test-rest-enqueue
  ports:
    - "5000:5000"
  env_file:
    - ./env.conf


