version: 2
jobs:
  azure:
    docker:
      - image: rgardler/simdem_cli:0.8.1

    steps:
      - checkout

      - run:
          name: Resource Group tests
          command: |
            simdem -p ./incubator/azure_compute/resource_group test

  kubernetes:
    docker:
      - image: rgardler/simdem_cli:0.8.1

    steps:
      - checkout

      - run:
          name: Create Kuberenetes Cluster
          no_output_timeout: "30m"
          command: |
            simdem -p ./kubernetes/create_cluster test

      - run:
          name: Connect to Kubernetes Cluster
          no_output_timeout: "30m"
          command: |
            simdem -p ./kubernetes/proxy test

      - run:
          name: Scale a Kubernetes Cluster
          no_output_timeout: "30m"
          command: |
            simdem -p ./kubernetes/scale test

      - run:
          name: Delete Kubernetes Cluster
          no_output_timeout: "30m"
          command: |
            simdem -p ./kubernetes/delete_cluster test

  biglittlechallenge:
    docker:
      - image: rgardler/simdem_cli:0.8.1

    steps:
      - checkout

      - run:
          name: install
          command: |
            simdem -p ./BigLittleChallenage/docs/install test

      - run:
          name: play_ai
          command: |
            simdem -p ./BigLittleChallenage/docs/play_ai_only test

      - run:
          name: uninstall
          command: |
            simdem -p ./BigLittleChallenage/docs/uninstall test
  
  dcos:
    docker:
      - image: rgardler/simdem_cli:0.8.1

    steps:
      - checkout

      - run:
          name: DC/OS tests
          no_output_timeout: "30m"
          command: |
            simdem -p ./dcos test

  aci:
    docker:
      - image: rgardler/simdem_cli:0.8.1

    steps:
      - checkout

      - run:
          name: ACI tests
          command: |
            simdem -p ./incubator/aci test

workflows:
  version: 2
  build_and_test:
    jobs:
      - azure
      - kubernetes:
          requires:
            - azure
      - dcos:
          requires:
            - azure
      - aci:
          requires:
            - azure
      - biglittlechallenge:
          requires:
            - kubernetes

