version: 2
jobs:
  build:
    docker:
      - image: rgardler/simdem_cli:0.8.1-dev

    steps:
      - checkout
        
      - run:
          name: run sample test
          command: |
            simdem -p . test

      - run:
          name: run Kubernetes tests
          no_output_timeout: "30m"
          command: |
            simdem -p ./kubernetes --fastfail false test
