version: 2
jobs:
  build:
    docker:
      - image: rgardler/simdem_cli:0.7.3

    steps:
      - checkout
        
      - run:
          name: run hello world tests
          command: |
            simdem -p . test
