version: 2
jobs:
  build:
    docker:
      - image: rgardler/simdem_cli:0.8.1-dev

    steps:
      - checkout
        
      - run:
          name: Hello World test
          command: |
            simdem -p . test
            
  azure:
    docker:
      - image: rgardler/simdem_cli:0.8.1-dev

    steps:
      - checkout

      - run:
          name: Resource Group tests
          command: |
            simdem -p ./incubator/azure_compute/resource_group test

  kubernetes:
    docker:
      - image: rgardler/simdem_cli:0.8.1-dev

    steps:
      - checkout

      - run:
          name: Kuberenetes tests
          no_output_timeout: "30m"
          command: |
            simdem -p ./kubernetes test

  dcos:
    docker:
      - image: rgardler/simdem_cli:0.8.1-dev

    steps:
      - checkout

      - run:
          name: DC/OS tests
          no_output_timeout: "30m"
          command: |
            simdem -p ./dcos test

  aci:
    docker:
      - image: rgardler/simdem_cli:0.8.1-dev

    steps:
      - checkout

      - run:
          name: ACI tests
          command: |
            simdem -p ./incubator/aci test

  vamp_kubernetes:
    docker:
      - image: rgardler/simdem_cli:0.8.1-dev

    steps:
      - checkout

      - run:
          name: Vamp tests
          command: |
            simdem -p ./vamp/kubernetes test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - azure:
          requires:
            - build
      - kubernetes:
          requires:
            - azure
      - dcos:
          requires:
            - azure
      - aci:
          requires:
            - azure
      - vamp_kubernetes:
          requires:
            - kubernetes

