apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aci-connector
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: aci-connector
    spec:
      containers:
      - name: aci-connector
        image: microsoft/aci-connector-k8s:latest
        imagePullPolicy: Always
        env:
        - name: AZURE_CLIENT_ID
          value: $(echo $SP_JSON | jq -r '.appId') 
        - name: AZURE_CLIENT_KEY
          value: $(echo $SP_JSON | jq -r '.password')
        - name: AZURE_TENANT_ID
          value: $(az account show | jq -r '.tenantId')
        - name: AZURE_SUBSCRIPTION_ID
          value: $(az account show | jq -r '.id')
        - name: ACI_RESOURCE_GROUP
          value: $SIMDEM_RESOURCE_GROUP
