apiVersion: v1
kind: Service
metadata:
  labels:
    service: engine
  name: engine
  namespace: default
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    service: engine
  sessionAffinity: None
  type: ClusterIP

