Master:
  Memory: "512Mi"
  HostName: rgjenkins.eastus.cloudapp.azure.com
  ServiceType: LoadBalancer 
  InstallPlugins:
      - kubernetes:0.11
      - workflow-aggregator:2.5
      - credentials-binding:1.11
      - git:3.2.0
      - pipeline-github-lib:1.0
      - ghprb:1.36.1
      - blueocean:1.0.1

ScriptApproval:
    - "method groovy.json.JsonSlurperClassic parseText java.lang.String"
    - "new groovy.json.JsonSlurperClassic"
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods leftShift java.util.Map java.util.Map"
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods split java.lang.String"

Agent:
  Enabled: false